=== bdpx/bdpx.github.io/xml/lab3/sonnet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="sonnet">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="author"/>
        <xsd:element ref="title" minOccurs="0"/>
        <xsd:element ref="lines"/>
      </xsd:sequence>
      <xsd:attribute name="type" type="sonnetType"
        default="Shakespearean"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="sonnetType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Petrarchan"/>
      <xsd:enumeration value="Shakespearean"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="author">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="lastName"/>
        <xsd:element ref="firstName"/>
        <xsd:element ref="nationality"/>
        <xsd:element ref="yearOfBirth" minOccurs="0"/>
        <xsd:element ref="yearOfDeath" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="lastName" type="xsd:string"/>
  <xsd:element name="firstName" type="xsd:string"/>
  <xsd:element name="nationality" type="xsd:string"/>
  <xsd:element name="yearOfBirth" type="xsd:string"/>
  <xsd:element name="yearOfDeath" type="xsd:string"/>

  <xsd:element name="title" type="xsd:string"/>

  <xsd:element name="lines">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="line" minOccurs="14" maxOccurs="14"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="line" type="xsd:string"/>
</xsd:schema>

=== bdpx/bdpx.github.io/xml/lab3/sonnet.xml
<?xml version="1.0"?>
<sonnet 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="sonnet.xsd"
  type="Shakespearean">
  <author>
    <lastName>Shakespeare</lastName>
    <firstName>William</firstName>
    <nationality>British</nationality>
    <yearOfBirth>1564</yearOfBirth>
    <yearOfDeath>1616</yearOfDeath>
  </author>
  <title>Sonnet 130</title>
  <lines>
    <line>My mistress' eyes are nothing like the sun,</line>
    <line>Coral is far more red than her lips red.</line>
    <line>If snow be white, why then her breasts are dun,</line>
    <line>If hairs be wires, black wires grow on her head.</line>
    <line>I have seen roses damasked, red and white,</line>
    <line>But no such roses see I in her cheeks.</line>
    <line>And in some perfumes is there more delight</line>
    <line>Than in the breath that from my mistress reeks.</line>
    <line>I love to hear her speak, yet well I know</line>
    <line>That music hath a far more pleasing sound.</line>
    <line>I grant I never saw a goddess go,</line>
    <line>My mistress when she walks, treads on the ground.</line>
    <line>And yet, by Heaven, I think my love as rare</line>
    <line>As any she belied with false compare.</line>
  </lines>
</sonnet>
